#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lemonldap-Portal-Authntsso
version:      0.02
version_from: Authntsso.pm
installdirs:  site
requires:
    Authen::Smb:                   0.0
    Net::Ldap:                     0.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
